{% set name = "xtensor-julia" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/QuantStack/xtensor-julia/archive/{{ version }}.tar.gz
  sha256: c62d23365d02cc463155347042cf830d4c09ac4c79bc7bdd5d18d21c0c8ba802 

build:
  number: 1
  # Julia and libcxxwrap-julia have not been packaged for conda on Windows
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
  host:
    - xtl >=0.6.9,<0.7
    - xtensor >=0.21.2,<0.22
    - libcxxwrap-julia >=0.5.3,<0.6
  run:
    - {{ pin_compatible('xtl', max_pin='x.x') }}
    - {{ pin_compatible('xtensor', max_pin='x.x') }}

test:
  commands:
    - test -d ${PREFIX}/include/xtensor-julia  # [unix]
    - test -f ${PREFIX}/include/xtensor-julia/jlarray.hpp  # [unix]
    - test -f ${PREFIX}/lib/cmake/xtensor-julia/xtensor-juliaConfig.cmake  # [unix]
    - test -f ${PREFIX}/lib/cmake/xtensor-julia/xtensor-juliaConfigVersion.cmake  # [unix]
    - if not exist %LIBRARY_PREFIX%\include\xtensor-julia\jlarray.hpp (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\lib\cmake\xtensor-julia\xtensor-juliaConfig.cmake (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\lib\cmake\xtensor-julia\xtensor-juliaConfigVersion.cmake (exit 1)  # [win]

about:
  home: http://quantstack.net/xtensor
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Julia bindings for the xtensor C++ multi-dimensional array library.'
  description: 'Multi dimensional arrays with broadcasting and lazy computing'
  doc_url: http://xtensor-julia.readthedocs.io
  dev_url: https://github.com/QuantStack/xtensor-julia

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - wolfv
    - davidbrochart
