travis:
  secure:
    BINSTAR_TOKEN: jbOoESrWT6QINecXwXqp1RkfrUfRFi6AqIHWYeBOTHlXIAtK9y4vwUZ8DTyiwXVIcmyaAInX7YmhIKCpgCGGU/TnPu3dkl81X0SM6EhVz7fGRHfzolOugKlOB/2xcz6eNAZAceGZKFS7Z9zF4u0zVWUXzBBKbQ1jT/3WuHUFf0YtFwL3vScAPsVuN0TqwcSlP0pdzssMjr6nBpRWQa3uSBmWKu5kTxpmGixfmERUq0ehXdEG6CZJDgM3O80Egnqcb9EYqZ96ACEfSC/0JvBcMffO37pus/NEwz2ghQ+y6cdsRj+14TJBmKvxlbXUDSzo2A2HqfOylI6n3CVhKrlxroAXdn11Z2DXmW1EKljFx07UGgYZ8/v7XhGBSSKbnF8f2q0FMUdiNTvU0JqjvchdK+kmfCPC4a+hTgHi4kGuUkdv0SN8ZESSK1qEilbk8ZZs9GlP+y53YKq97z3Yu1bypo95beLvaWRd1RDZ/XkRIjGQnU83zNM5ZPsveOihrQnfE2oiNf7vzS9GsggkyN2rkidzjjJ2i+z8e0S/uYfNxDCe1DsYqSxXPJOFFiIRcbv2QZOWiX1fYr88COhjoaVyuMgSRxg9CBw0Il7icMOSiFLgE1ukMaoM0+QXSkWzGW8uxuRLVIPRap3LSLXMxYAffRI1Xr9CoMHvfcLjp9vPNEg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
